stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - docker-helpdesk
  image: docker:29.4.1-dind
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  before_script:
    - docker info
    - docker compose version
  script:
    - cd /home/katondaru/helpdesk-fix
    - git fetch origin
    - git reset --hard origin/main
    - git clean -fd
    - docker compose pull
    - docker compose up -d --remove-orphans
  only:
    - main
