name: Deploy Helpdesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest code
        run: |
          cd /home/katondaru/helpdesk-fix
          git fetch https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/katondaru-dts/helpdesk-fix.git main
          git reset --hard FETCH_HEAD
          git clean -fd

      - name: Deploy dengan Docker Compose
        run: |
          cd /home/katondaru/helpdesk-fix
          docker compose pull
          docker compose up -d --remove-orphans
      - name: Run Database Migrations & Clear Cache
        run: |
          docker exec -T helpdesk-app php spark migrate --all
          docker exec -T helpdesk-app php spark cache:clear
      - name: Fix Permissions
        run: |
          docker exec -T helpdesk-app chown -R www-data:www-data writable
          docker exec -T helpdesk-app chmod -R 777 writable