name: Deploy Helpdesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest code
        run: |
          cd /home/katondaru/helpdesk-fix
          git fetch https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/katondaru-dts/helpdesk-fix.git main
          git reset --hard FETCH_HEAD
          git clean -fd --exclude=writable

      - name: Deploy dengan Docker Compose
        run: |
          cd /home/katondaru/helpdesk-fix
          docker compose pull
          docker compose up -d --remove-orphans

      - name: Prepare Writable Directories
        run: |
          docker exec helpdesk-app mkdir -p /var/www/html/writable/cache /var/www/html/writable/logs /var/www/html/writable/session /var/www/html/writable/debugbar

      - name: Run Database Migrations & Clear Cache
        run: |
          docker exec helpdesk-app php spark migrate --all
          docker exec helpdesk-app php spark cache:clear